name: ffn_example_ds_launcher
workspace: DS_AT_PROTOTYPING
project: ffn_example
max_restarts: 0
environment:
  image:
    gpu: determinedai/environments:cuda-11.3-pytorch-1.10-tf-2.8-deepspeed-0.7.0-gpu-0.20.1
    cpu: determinedai/environments:cuda-11.3-pytorch-1.10-tf-2.8-deepspeed-0.7.0-gpu-0.20.1
resources:
  slots_per_trial: 2
  shm_size: 17179869184 # 16 GiB. Was hitting "Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm)."
  max_slots: 8
  # resource_pool: young # Grenoble specific; remove later.
searcher:
  name: single
  max_length: 10
  metric: placeholder
hyperparameters:
  dim: 4096
  layers: 8 # Total params will be layers * dim ** 2
  deepspeed_config: ds_config.json
entrypoint: python3 -m determined.launch.deepspeed python3 script.py
